ADD_SCENE(weather_station, start, Start)
ADD_SCENE(weather_station, about, About)
ADD_SCENE(weather_station, settings, Settings)
ADD_SCENE(weather_station, saved_profiles, SavedProfiles)
ADD_SCENE(weather_station, simulation, Simulation)
ADD_SCENE(weather_station, receiver, Receiver)
ADD_SCENE(weather_station, receiver_config, ReceiverConfig)
ADD_SCENE(weather_station, receiver_info, ReceiverInfo)
ADD_SCENE(weather_station, actions, Actions)
ADD_SCENE(weather_station, action_result, ActionResult)
ADD_SCENE(weather_station, number_input, NumberInput)

ADD_SCENE(weather_station, lab_pin, LabPin)
ADD_SCENE(weather_station, lab_config, LabConfig)
ADD_SCENE(weather_station, lab_run, LabRun)
