// AUTO-GENERATED by gen_hell_kernels.py -- DO NOT EDIT.
// Per-round specialized bitsliced filter/LFSR kernels with
// compile-time-constant state[] indices. Bit-identical to the
// original runtime-index bs_filter_at / bs_lfsr_at.
//
// Requires (before #include): bitslice_t, STATE_ARR_LEN,
// f_a_bs, f_b_bs, f_c_bs.
#ifndef HELL_KERNELS_GEN_H
#define HELL_KERNELS_GEN_H

// ---- Per-round filter kernels ----
static inline bitslice_t bs_filter_at_r0(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[45], state[44], state[42], state[41]);
    const bitslice_t g1 = f_b_bs(state[39], state[35], state[33], state[32]);
    const bitslice_t g2 = f_b_bs(state[30], state[26], state[24], state[21]);
    const bitslice_t g3 = f_b_bs(state[19], state[18], state[16], state[14]);
    const bitslice_t g4 = f_a_bs(state[13], state[4], state[3], state[1]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r1(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[44], state[43], state[41], state[40]);
    const bitslice_t g1 = f_b_bs(state[38], state[34], state[32], state[31]);
    const bitslice_t g2 = f_b_bs(state[29], state[25], state[23], state[20]);
    const bitslice_t g3 = f_b_bs(state[18], state[17], state[15], state[13]);
    const bitslice_t g4 = f_a_bs(state[12], state[3], state[2], state[0]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r2(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[43], state[42], state[40], state[39]);
    const bitslice_t g1 = f_b_bs(state[37], state[33], state[31], state[30]);
    const bitslice_t g2 = f_b_bs(state[28], state[24], state[22], state[19]);
    const bitslice_t g3 = f_b_bs(state[17], state[16], state[14], state[12]);
    const bitslice_t g4 = f_a_bs(state[11], state[2], state[1], state[48]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r3(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[42], state[41], state[39], state[38]);
    const bitslice_t g1 = f_b_bs(state[36], state[32], state[30], state[29]);
    const bitslice_t g2 = f_b_bs(state[27], state[23], state[21], state[18]);
    const bitslice_t g3 = f_b_bs(state[16], state[15], state[13], state[11]);
    const bitslice_t g4 = f_a_bs(state[10], state[1], state[0], state[49]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r4(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[41], state[40], state[38], state[37]);
    const bitslice_t g1 = f_b_bs(state[35], state[31], state[29], state[28]);
    const bitslice_t g2 = f_b_bs(state[26], state[22], state[20], state[17]);
    const bitslice_t g3 = f_b_bs(state[15], state[14], state[12], state[10]);
    const bitslice_t g4 = f_a_bs(state[9], state[0], state[48], state[50]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r5(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[40], state[39], state[37], state[36]);
    const bitslice_t g1 = f_b_bs(state[34], state[30], state[28], state[27]);
    const bitslice_t g2 = f_b_bs(state[25], state[21], state[19], state[16]);
    const bitslice_t g3 = f_b_bs(state[14], state[13], state[11], state[9]);
    const bitslice_t g4 = f_a_bs(state[8], state[48], state[49], state[51]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r6(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[39], state[38], state[36], state[35]);
    const bitslice_t g1 = f_b_bs(state[33], state[29], state[27], state[26]);
    const bitslice_t g2 = f_b_bs(state[24], state[20], state[18], state[15]);
    const bitslice_t g3 = f_b_bs(state[13], state[12], state[10], state[8]);
    const bitslice_t g4 = f_a_bs(state[7], state[49], state[50], state[52]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r7(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[38], state[37], state[35], state[34]);
    const bitslice_t g1 = f_b_bs(state[32], state[28], state[26], state[25]);
    const bitslice_t g2 = f_b_bs(state[23], state[19], state[17], state[14]);
    const bitslice_t g3 = f_b_bs(state[12], state[11], state[9], state[7]);
    const bitslice_t g4 = f_a_bs(state[6], state[50], state[51], state[53]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r8(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[37], state[36], state[34], state[33]);
    const bitslice_t g1 = f_b_bs(state[31], state[27], state[25], state[24]);
    const bitslice_t g2 = f_b_bs(state[22], state[18], state[16], state[13]);
    const bitslice_t g3 = f_b_bs(state[11], state[10], state[8], state[6]);
    const bitslice_t g4 = f_a_bs(state[5], state[51], state[52], state[54]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r9(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[36], state[35], state[33], state[32]);
    const bitslice_t g1 = f_b_bs(state[30], state[26], state[24], state[23]);
    const bitslice_t g2 = f_b_bs(state[21], state[17], state[15], state[12]);
    const bitslice_t g3 = f_b_bs(state[10], state[9], state[7], state[5]);
    const bitslice_t g4 = f_a_bs(state[4], state[52], state[53], state[55]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r10(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[35], state[34], state[32], state[31]);
    const bitslice_t g1 = f_b_bs(state[29], state[25], state[23], state[22]);
    const bitslice_t g2 = f_b_bs(state[20], state[16], state[14], state[11]);
    const bitslice_t g3 = f_b_bs(state[9], state[8], state[6], state[4]);
    const bitslice_t g4 = f_a_bs(state[3], state[53], state[54], state[56]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r11(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[34], state[33], state[31], state[30]);
    const bitslice_t g1 = f_b_bs(state[28], state[24], state[22], state[21]);
    const bitslice_t g2 = f_b_bs(state[19], state[15], state[13], state[10]);
    const bitslice_t g3 = f_b_bs(state[8], state[7], state[5], state[3]);
    const bitslice_t g4 = f_a_bs(state[2], state[54], state[55], state[57]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r12(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[33], state[32], state[30], state[29]);
    const bitslice_t g1 = f_b_bs(state[27], state[23], state[21], state[20]);
    const bitslice_t g2 = f_b_bs(state[18], state[14], state[12], state[9]);
    const bitslice_t g3 = f_b_bs(state[7], state[6], state[4], state[2]);
    const bitslice_t g4 = f_a_bs(state[1], state[55], state[56], state[58]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r13(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[32], state[31], state[29], state[28]);
    const bitslice_t g1 = f_b_bs(state[26], state[22], state[20], state[19]);
    const bitslice_t g2 = f_b_bs(state[17], state[13], state[11], state[8]);
    const bitslice_t g3 = f_b_bs(state[6], state[5], state[3], state[1]);
    const bitslice_t g4 = f_a_bs(state[0], state[56], state[57], state[59]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r14(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[31], state[30], state[28], state[27]);
    const bitslice_t g1 = f_b_bs(state[25], state[21], state[19], state[18]);
    const bitslice_t g2 = f_b_bs(state[16], state[12], state[10], state[7]);
    const bitslice_t g3 = f_b_bs(state[5], state[4], state[2], state[0]);
    const bitslice_t g4 = f_a_bs(state[48], state[57], state[58], state[60]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r15(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[30], state[29], state[27], state[26]);
    const bitslice_t g1 = f_b_bs(state[24], state[20], state[18], state[17]);
    const bitslice_t g2 = f_b_bs(state[15], state[11], state[9], state[6]);
    const bitslice_t g3 = f_b_bs(state[4], state[3], state[1], state[48]);
    const bitslice_t g4 = f_a_bs(state[49], state[58], state[59], state[61]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r16(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[29], state[28], state[26], state[25]);
    const bitslice_t g1 = f_b_bs(state[23], state[19], state[17], state[16]);
    const bitslice_t g2 = f_b_bs(state[14], state[10], state[8], state[5]);
    const bitslice_t g3 = f_b_bs(state[3], state[2], state[0], state[49]);
    const bitslice_t g4 = f_a_bs(state[50], state[59], state[60], state[62]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r17(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[28], state[27], state[25], state[24]);
    const bitslice_t g1 = f_b_bs(state[22], state[18], state[16], state[15]);
    const bitslice_t g2 = f_b_bs(state[13], state[9], state[7], state[4]);
    const bitslice_t g3 = f_b_bs(state[2], state[1], state[48], state[50]);
    const bitslice_t g4 = f_a_bs(state[51], state[60], state[61], state[63]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r18(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[27], state[26], state[24], state[23]);
    const bitslice_t g1 = f_b_bs(state[21], state[17], state[15], state[14]);
    const bitslice_t g2 = f_b_bs(state[12], state[8], state[6], state[3]);
    const bitslice_t g3 = f_b_bs(state[1], state[0], state[49], state[51]);
    const bitslice_t g4 = f_a_bs(state[52], state[61], state[62], state[64]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r19(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[26], state[25], state[23], state[22]);
    const bitslice_t g1 = f_b_bs(state[20], state[16], state[14], state[13]);
    const bitslice_t g2 = f_b_bs(state[11], state[7], state[5], state[2]);
    const bitslice_t g3 = f_b_bs(state[0], state[48], state[50], state[52]);
    const bitslice_t g4 = f_a_bs(state[53], state[62], state[63], state[65]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r20(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[25], state[24], state[22], state[21]);
    const bitslice_t g1 = f_b_bs(state[19], state[15], state[13], state[12]);
    const bitslice_t g2 = f_b_bs(state[10], state[6], state[4], state[1]);
    const bitslice_t g3 = f_b_bs(state[48], state[49], state[51], state[53]);
    const bitslice_t g4 = f_a_bs(state[54], state[63], state[64], state[66]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r21(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[24], state[23], state[21], state[20]);
    const bitslice_t g1 = f_b_bs(state[18], state[14], state[12], state[11]);
    const bitslice_t g2 = f_b_bs(state[9], state[5], state[3], state[0]);
    const bitslice_t g3 = f_b_bs(state[49], state[50], state[52], state[54]);
    const bitslice_t g4 = f_a_bs(state[55], state[64], state[65], state[67]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r22(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[23], state[22], state[20], state[19]);
    const bitslice_t g1 = f_b_bs(state[17], state[13], state[11], state[10]);
    const bitslice_t g2 = f_b_bs(state[8], state[4], state[2], state[48]);
    const bitslice_t g3 = f_b_bs(state[50], state[51], state[53], state[55]);
    const bitslice_t g4 = f_a_bs(state[56], state[65], state[66], state[68]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r23(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[22], state[21], state[19], state[18]);
    const bitslice_t g1 = f_b_bs(state[16], state[12], state[10], state[9]);
    const bitslice_t g2 = f_b_bs(state[7], state[3], state[1], state[49]);
    const bitslice_t g3 = f_b_bs(state[51], state[52], state[54], state[56]);
    const bitslice_t g4 = f_a_bs(state[57], state[66], state[67], state[69]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r24(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[21], state[20], state[18], state[17]);
    const bitslice_t g1 = f_b_bs(state[15], state[11], state[9], state[8]);
    const bitslice_t g2 = f_b_bs(state[6], state[2], state[0], state[50]);
    const bitslice_t g3 = f_b_bs(state[52], state[53], state[55], state[57]);
    const bitslice_t g4 = f_a_bs(state[58], state[67], state[68], state[70]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r25(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[20], state[19], state[17], state[16]);
    const bitslice_t g1 = f_b_bs(state[14], state[10], state[8], state[7]);
    const bitslice_t g2 = f_b_bs(state[5], state[1], state[48], state[51]);
    const bitslice_t g3 = f_b_bs(state[53], state[54], state[56], state[58]);
    const bitslice_t g4 = f_a_bs(state[59], state[68], state[69], state[71]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r26(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[19], state[18], state[16], state[15]);
    const bitslice_t g1 = f_b_bs(state[13], state[9], state[7], state[6]);
    const bitslice_t g2 = f_b_bs(state[4], state[0], state[49], state[52]);
    const bitslice_t g3 = f_b_bs(state[54], state[55], state[57], state[59]);
    const bitslice_t g4 = f_a_bs(state[60], state[69], state[70], state[72]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r27(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[18], state[17], state[15], state[14]);
    const bitslice_t g1 = f_b_bs(state[12], state[8], state[6], state[5]);
    const bitslice_t g2 = f_b_bs(state[3], state[48], state[50], state[53]);
    const bitslice_t g3 = f_b_bs(state[55], state[56], state[58], state[60]);
    const bitslice_t g4 = f_a_bs(state[61], state[70], state[71], state[73]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r28(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[17], state[16], state[14], state[13]);
    const bitslice_t g1 = f_b_bs(state[11], state[7], state[5], state[4]);
    const bitslice_t g2 = f_b_bs(state[2], state[49], state[51], state[54]);
    const bitslice_t g3 = f_b_bs(state[56], state[57], state[59], state[61]);
    const bitslice_t g4 = f_a_bs(state[62], state[71], state[72], state[74]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r29(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[16], state[15], state[13], state[12]);
    const bitslice_t g1 = f_b_bs(state[10], state[6], state[4], state[3]);
    const bitslice_t g2 = f_b_bs(state[1], state[50], state[52], state[55]);
    const bitslice_t g3 = f_b_bs(state[57], state[58], state[60], state[62]);
    const bitslice_t g4 = f_a_bs(state[63], state[72], state[73], state[75]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r30(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[15], state[14], state[12], state[11]);
    const bitslice_t g1 = f_b_bs(state[9], state[5], state[3], state[2]);
    const bitslice_t g2 = f_b_bs(state[0], state[51], state[53], state[56]);
    const bitslice_t g3 = f_b_bs(state[58], state[59], state[61], state[63]);
    const bitslice_t g4 = f_a_bs(state[64], state[73], state[74], state[76]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

static inline bitslice_t bs_filter_at_r31(const bitslice_t state[STATE_ARR_LEN]) {
    const bitslice_t g0 = f_a_bs(state[14], state[13], state[11], state[10]);
    const bitslice_t g1 = f_b_bs(state[8], state[4], state[2], state[1]);
    const bitslice_t g2 = f_b_bs(state[48], state[52], state[54], state[57]);
    const bitslice_t g3 = f_b_bs(state[59], state[60], state[62], state[64]);
    const bitslice_t g4 = f_a_bs(state[65], state[74], state[75], state[77]);
    return f_c_bs(g0, g1, g2, g3, g4);
}

// ---- Per-round LFSR kernels ----
static inline bitslice_t bs_lfsr_at_r0(const bitslice_t state[STATE_ARR_LEN]) {
    return state[0] ^ state[1] ^ state[4] ^ state[5] ^ state[6] ^ state[17] ^ state[21] ^ state[24] ^ state[25] ^ state[31] ^ state[39] ^ state[40] ^ state[41] ^ state[44] ^ state[45] ^ state[47];
}

static inline bitslice_t bs_lfsr_at_r1(const bitslice_t state[STATE_ARR_LEN]) {
    return state[0] ^ state[3] ^ state[4] ^ state[5] ^ state[16] ^ state[20] ^ state[23] ^ state[24] ^ state[30] ^ state[38] ^ state[39] ^ state[40] ^ state[43] ^ state[44] ^ state[46] ^ state[48];
}

static inline bitslice_t bs_lfsr_at_r2(const bitslice_t state[STATE_ARR_LEN]) {
    return state[2] ^ state[3] ^ state[4] ^ state[15] ^ state[19] ^ state[22] ^ state[23] ^ state[29] ^ state[37] ^ state[38] ^ state[39] ^ state[42] ^ state[43] ^ state[45] ^ state[48] ^ state[49];
}

static inline bitslice_t bs_lfsr_at_r3(const bitslice_t state[STATE_ARR_LEN]) {
    return state[1] ^ state[2] ^ state[3] ^ state[14] ^ state[18] ^ state[21] ^ state[22] ^ state[28] ^ state[36] ^ state[37] ^ state[38] ^ state[41] ^ state[42] ^ state[44] ^ state[49] ^ state[50];
}

static inline bitslice_t bs_lfsr_at_r4(const bitslice_t state[STATE_ARR_LEN]) {
    return state[0] ^ state[1] ^ state[2] ^ state[13] ^ state[17] ^ state[20] ^ state[21] ^ state[27] ^ state[35] ^ state[36] ^ state[37] ^ state[40] ^ state[41] ^ state[43] ^ state[50] ^ state[51];
}

static inline bitslice_t bs_lfsr_at_r5(const bitslice_t state[STATE_ARR_LEN]) {
    return state[0] ^ state[1] ^ state[12] ^ state[16] ^ state[19] ^ state[20] ^ state[26] ^ state[34] ^ state[35] ^ state[36] ^ state[39] ^ state[40] ^ state[42] ^ state[48] ^ state[51] ^ state[52];
}

static inline bitslice_t bs_lfsr_at_r6(const bitslice_t state[STATE_ARR_LEN]) {
    return state[0] ^ state[11] ^ state[15] ^ state[18] ^ state[19] ^ state[25] ^ state[33] ^ state[34] ^ state[35] ^ state[38] ^ state[39] ^ state[41] ^ state[48] ^ state[49] ^ state[52] ^ state[53];
}

static inline bitslice_t bs_lfsr_at_r7(const bitslice_t state[STATE_ARR_LEN]) {
    return state[10] ^ state[14] ^ state[17] ^ state[18] ^ state[24] ^ state[32] ^ state[33] ^ state[34] ^ state[37] ^ state[38] ^ state[40] ^ state[48] ^ state[49] ^ state[50] ^ state[53] ^ state[54];
}

static inline bitslice_t bs_lfsr_at_r8(const bitslice_t state[STATE_ARR_LEN]) {
    return state[9] ^ state[13] ^ state[16] ^ state[17] ^ state[23] ^ state[31] ^ state[32] ^ state[33] ^ state[36] ^ state[37] ^ state[39] ^ state[49] ^ state[50] ^ state[51] ^ state[54] ^ state[55];
}

static inline bitslice_t bs_lfsr_at_r9(const bitslice_t state[STATE_ARR_LEN]) {
    return state[8] ^ state[12] ^ state[15] ^ state[16] ^ state[22] ^ state[30] ^ state[31] ^ state[32] ^ state[35] ^ state[36] ^ state[38] ^ state[50] ^ state[51] ^ state[52] ^ state[55] ^ state[56];
}

static inline bitslice_t bs_lfsr_at_r10(const bitslice_t state[STATE_ARR_LEN]) {
    return state[7] ^ state[11] ^ state[14] ^ state[15] ^ state[21] ^ state[29] ^ state[30] ^ state[31] ^ state[34] ^ state[35] ^ state[37] ^ state[51] ^ state[52] ^ state[53] ^ state[56] ^ state[57];
}

static inline bitslice_t bs_lfsr_at_r11(const bitslice_t state[STATE_ARR_LEN]) {
    return state[6] ^ state[10] ^ state[13] ^ state[14] ^ state[20] ^ state[28] ^ state[29] ^ state[30] ^ state[33] ^ state[34] ^ state[36] ^ state[52] ^ state[53] ^ state[54] ^ state[57] ^ state[58];
}

static inline bitslice_t bs_lfsr_at_r12(const bitslice_t state[STATE_ARR_LEN]) {
    return state[5] ^ state[9] ^ state[12] ^ state[13] ^ state[19] ^ state[27] ^ state[28] ^ state[29] ^ state[32] ^ state[33] ^ state[35] ^ state[53] ^ state[54] ^ state[55] ^ state[58] ^ state[59];
}

static inline bitslice_t bs_lfsr_at_r13(const bitslice_t state[STATE_ARR_LEN]) {
    return state[4] ^ state[8] ^ state[11] ^ state[12] ^ state[18] ^ state[26] ^ state[27] ^ state[28] ^ state[31] ^ state[32] ^ state[34] ^ state[54] ^ state[55] ^ state[56] ^ state[59] ^ state[60];
}

static inline bitslice_t bs_lfsr_at_r14(const bitslice_t state[STATE_ARR_LEN]) {
    return state[3] ^ state[7] ^ state[10] ^ state[11] ^ state[17] ^ state[25] ^ state[26] ^ state[27] ^ state[30] ^ state[31] ^ state[33] ^ state[55] ^ state[56] ^ state[57] ^ state[60] ^ state[61];
}

static inline bitslice_t bs_lfsr_at_r15(const bitslice_t state[STATE_ARR_LEN]) {
    return state[2] ^ state[6] ^ state[9] ^ state[10] ^ state[16] ^ state[24] ^ state[25] ^ state[26] ^ state[29] ^ state[30] ^ state[32] ^ state[56] ^ state[57] ^ state[58] ^ state[61] ^ state[62];
}

static inline bitslice_t bs_lfsr_at_r16(const bitslice_t state[STATE_ARR_LEN]) {
    return state[1] ^ state[5] ^ state[8] ^ state[9] ^ state[15] ^ state[23] ^ state[24] ^ state[25] ^ state[28] ^ state[29] ^ state[31] ^ state[57] ^ state[58] ^ state[59] ^ state[62] ^ state[63];
}

static inline bitslice_t bs_lfsr_at_r17(const bitslice_t state[STATE_ARR_LEN]) {
    return state[0] ^ state[4] ^ state[7] ^ state[8] ^ state[14] ^ state[22] ^ state[23] ^ state[24] ^ state[27] ^ state[28] ^ state[30] ^ state[58] ^ state[59] ^ state[60] ^ state[63] ^ state[64];
}

static inline bitslice_t bs_lfsr_at_r18(const bitslice_t state[STATE_ARR_LEN]) {
    return state[3] ^ state[6] ^ state[7] ^ state[13] ^ state[21] ^ state[22] ^ state[23] ^ state[26] ^ state[27] ^ state[29] ^ state[48] ^ state[59] ^ state[60] ^ state[61] ^ state[64] ^ state[65];
}

static inline bitslice_t bs_lfsr_at_r19(const bitslice_t state[STATE_ARR_LEN]) {
    return state[2] ^ state[5] ^ state[6] ^ state[12] ^ state[20] ^ state[21] ^ state[22] ^ state[25] ^ state[26] ^ state[28] ^ state[49] ^ state[60] ^ state[61] ^ state[62] ^ state[65] ^ state[66];
}

static inline bitslice_t bs_lfsr_at_r20(const bitslice_t state[STATE_ARR_LEN]) {
    return state[1] ^ state[4] ^ state[5] ^ state[11] ^ state[19] ^ state[20] ^ state[21] ^ state[24] ^ state[25] ^ state[27] ^ state[50] ^ state[61] ^ state[62] ^ state[63] ^ state[66] ^ state[67];
}

static inline bitslice_t bs_lfsr_at_r21(const bitslice_t state[STATE_ARR_LEN]) {
    return state[0] ^ state[3] ^ state[4] ^ state[10] ^ state[18] ^ state[19] ^ state[20] ^ state[23] ^ state[24] ^ state[26] ^ state[51] ^ state[62] ^ state[63] ^ state[64] ^ state[67] ^ state[68];
}

static inline bitslice_t bs_lfsr_at_r22(const bitslice_t state[STATE_ARR_LEN]) {
    return state[2] ^ state[3] ^ state[9] ^ state[17] ^ state[18] ^ state[19] ^ state[22] ^ state[23] ^ state[25] ^ state[48] ^ state[52] ^ state[63] ^ state[64] ^ state[65] ^ state[68] ^ state[69];
}

static inline bitslice_t bs_lfsr_at_r23(const bitslice_t state[STATE_ARR_LEN]) {
    return state[1] ^ state[2] ^ state[8] ^ state[16] ^ state[17] ^ state[18] ^ state[21] ^ state[22] ^ state[24] ^ state[49] ^ state[53] ^ state[64] ^ state[65] ^ state[66] ^ state[69] ^ state[70];
}

static inline bitslice_t bs_lfsr_at_r24(const bitslice_t state[STATE_ARR_LEN]) {
    return state[0] ^ state[1] ^ state[7] ^ state[15] ^ state[16] ^ state[17] ^ state[20] ^ state[21] ^ state[23] ^ state[50] ^ state[54] ^ state[65] ^ state[66] ^ state[67] ^ state[70] ^ state[71];
}

static inline bitslice_t bs_lfsr_at_r25(const bitslice_t state[STATE_ARR_LEN]) {
    return state[0] ^ state[6] ^ state[14] ^ state[15] ^ state[16] ^ state[19] ^ state[20] ^ state[22] ^ state[48] ^ state[51] ^ state[55] ^ state[66] ^ state[67] ^ state[68] ^ state[71] ^ state[72];
}

static inline bitslice_t bs_lfsr_at_r26(const bitslice_t state[STATE_ARR_LEN]) {
    return state[5] ^ state[13] ^ state[14] ^ state[15] ^ state[18] ^ state[19] ^ state[21] ^ state[48] ^ state[49] ^ state[52] ^ state[56] ^ state[67] ^ state[68] ^ state[69] ^ state[72] ^ state[73];
}

static inline bitslice_t bs_lfsr_at_r27(const bitslice_t state[STATE_ARR_LEN]) {
    return state[4] ^ state[12] ^ state[13] ^ state[14] ^ state[17] ^ state[18] ^ state[20] ^ state[49] ^ state[50] ^ state[53] ^ state[57] ^ state[68] ^ state[69] ^ state[70] ^ state[73] ^ state[74];
}

static inline bitslice_t bs_lfsr_at_r28(const bitslice_t state[STATE_ARR_LEN]) {
    return state[3] ^ state[11] ^ state[12] ^ state[13] ^ state[16] ^ state[17] ^ state[19] ^ state[50] ^ state[51] ^ state[54] ^ state[58] ^ state[69] ^ state[70] ^ state[71] ^ state[74] ^ state[75];
}

static inline bitslice_t bs_lfsr_at_r29(const bitslice_t state[STATE_ARR_LEN]) {
    return state[2] ^ state[10] ^ state[11] ^ state[12] ^ state[15] ^ state[16] ^ state[18] ^ state[51] ^ state[52] ^ state[55] ^ state[59] ^ state[70] ^ state[71] ^ state[72] ^ state[75] ^ state[76];
}

static inline bitslice_t bs_lfsr_at_r30(const bitslice_t state[STATE_ARR_LEN]) {
    return state[1] ^ state[9] ^ state[10] ^ state[11] ^ state[14] ^ state[15] ^ state[17] ^ state[52] ^ state[53] ^ state[56] ^ state[60] ^ state[71] ^ state[72] ^ state[73] ^ state[76] ^ state[77];
}

static inline bitslice_t bs_lfsr_at_r31(const bitslice_t state[STATE_ARR_LEN]) {
    return state[0] ^ state[8] ^ state[9] ^ state[10] ^ state[13] ^ state[14] ^ state[16] ^ state[53] ^ state[54] ^ state[57] ^ state[61] ^ state[72] ^ state[73] ^ state[74] ^ state[77] ^ state[78];
}

// ---- Dispatchers (jump-table for variable r) ----
static inline bitslice_t bs_filter_at(const bitslice_t state[STATE_ARR_LEN], uint8_t r) {
    switch(r) {
        case 0: return bs_filter_at_r0(state);
        case 1: return bs_filter_at_r1(state);
        case 2: return bs_filter_at_r2(state);
        case 3: return bs_filter_at_r3(state);
        case 4: return bs_filter_at_r4(state);
        case 5: return bs_filter_at_r5(state);
        case 6: return bs_filter_at_r6(state);
        case 7: return bs_filter_at_r7(state);
        case 8: return bs_filter_at_r8(state);
        case 9: return bs_filter_at_r9(state);
        case 10: return bs_filter_at_r10(state);
        case 11: return bs_filter_at_r11(state);
        case 12: return bs_filter_at_r12(state);
        case 13: return bs_filter_at_r13(state);
        case 14: return bs_filter_at_r14(state);
        case 15: return bs_filter_at_r15(state);
        case 16: return bs_filter_at_r16(state);
        case 17: return bs_filter_at_r17(state);
        case 18: return bs_filter_at_r18(state);
        case 19: return bs_filter_at_r19(state);
        case 20: return bs_filter_at_r20(state);
        case 21: return bs_filter_at_r21(state);
        case 22: return bs_filter_at_r22(state);
        case 23: return bs_filter_at_r23(state);
        case 24: return bs_filter_at_r24(state);
        case 25: return bs_filter_at_r25(state);
        case 26: return bs_filter_at_r26(state);
        case 27: return bs_filter_at_r27(state);
        case 28: return bs_filter_at_r28(state);
        case 29: return bs_filter_at_r29(state);
        case 30: return bs_filter_at_r30(state);
        case 31: return bs_filter_at_r31(state);
        default: return 0;
    }
}

static inline bitslice_t bs_lfsr_at(const bitslice_t state[STATE_ARR_LEN], uint8_t r) {
    switch(r) {
        case 0: return bs_lfsr_at_r0(state);
        case 1: return bs_lfsr_at_r1(state);
        case 2: return bs_lfsr_at_r2(state);
        case 3: return bs_lfsr_at_r3(state);
        case 4: return bs_lfsr_at_r4(state);
        case 5: return bs_lfsr_at_r5(state);
        case 6: return bs_lfsr_at_r6(state);
        case 7: return bs_lfsr_at_r7(state);
        case 8: return bs_lfsr_at_r8(state);
        case 9: return bs_lfsr_at_r9(state);
        case 10: return bs_lfsr_at_r10(state);
        case 11: return bs_lfsr_at_r11(state);
        case 12: return bs_lfsr_at_r12(state);
        case 13: return bs_lfsr_at_r13(state);
        case 14: return bs_lfsr_at_r14(state);
        case 15: return bs_lfsr_at_r15(state);
        case 16: return bs_lfsr_at_r16(state);
        case 17: return bs_lfsr_at_r17(state);
        case 18: return bs_lfsr_at_r18(state);
        case 19: return bs_lfsr_at_r19(state);
        case 20: return bs_lfsr_at_r20(state);
        case 21: return bs_lfsr_at_r21(state);
        case 22: return bs_lfsr_at_r22(state);
        case 23: return bs_lfsr_at_r23(state);
        case 24: return bs_lfsr_at_r24(state);
        case 25: return bs_lfsr_at_r25(state);
        case 26: return bs_lfsr_at_r26(state);
        case 27: return bs_lfsr_at_r27(state);
        case 28: return bs_lfsr_at_r28(state);
        case 29: return bs_lfsr_at_r29(state);
        case 30: return bs_lfsr_at_r30(state);
        case 31: return bs_lfsr_at_r31(state);
        default: return 0;
    }
}

#endif // HELL_KERNELS_GEN_H
